version: "3.9"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    stdin_open: true # Interactive shell
    tty: true
    network_mode: host # Networking and IPC for ROS 2
    ipc: host
    privileged: true # Needed to display graphical applications
    volumes:
      - "/dev:/dev"
    device_cgroup_rules:
      - 'c *:* mrw'

  aria_node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - "/dev:/dev"
    device_cgroup_rules:
      - 'c *:* mrw'
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    command: /bin/bash -c "source ./install/setup.bash && ros2 run ariaNode ariaNode -rp /dev/ttyUSB0"
  other_nodes:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - "/dev:/dev"
    device_cgroup_rules:
      - 'c *:* mrw'
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    command: /bin/bash -c "source ./install/setup.bash && ros2 launch otherNodes launch.py"
