ekf_filter_node:
    ros__parameters:
        frequency: 20.0
        sensor_timeout: 0.1
        two_d_mode: true
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true
        debug: false
        permit_corrected_publication: false
        publish_acceleration: false
        publish_tf: true

        map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" if unspecified
        world_frame: odom           # Defaults to the value of odom_frame if unspecified

        imu0: /transformed_imu
        imu0_config: [
            false, false, false, # X, Y, Z
            false, false, false,  # roll, pitch, yaw
            false, false, false,   # dX, dY, dZ
            false, false, true, # dr, dp, dy
            true, false, false  # ddX, ddY, ddZ
        ]
        imu0_differential: false
        imu0_relative: true
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true

        twist0: /robot_twist
        twist0_config: [
            false, false, false, # X, Y, Z
            false, false, false,  # roll, pitch, yaw
            true, true, false,   # dX, dY, dZ
            false, false, true, # dr, dp, dy
            false, false, false  # ddX, ddY, ddZ
        ]
        twist0_differential: false
        twist0_relative: true
        twist0_queue_size: 10
        twist0_remove_gravitational_acceleration: true

        use_control: true
        stamped_control: false
        control_timeout: 0.2
        control_config: [true, false, false, false, false, true]
        acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.4]
        deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 4.5]
        acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
        deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]