joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0
    dev: '/dev/input/js0'
    

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5

    require_enable_button: false
